name: Update Submodule on Dispatch

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # 서브모듈 포함하여 체크아웃
      - name: Update Submodules
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git submodule update --init --remote --rebase
          git add .  # 변경 사항 모두 추가 (서브모듈 및 상위 저장소)
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update submodules"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions에서 제공하는 토큰
